language: ruby
dist: focal
rvm:
  - 2.7.0
install: gem install asciidoctor-pdf --pre

git:
  depth: 1
branches:
  only:
    - main
addons:
  apt:
    packages:
      - zsh
env:
  global:
    - ENCRYPTION_LABEL: "189e52c2c347"
    - COMMIT_AUTHOR_EMAIL: "sall@w-ss.io"
before_script:
  - zsh --version
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in share/deploy_key.enc -out share/deploy_key -d
script:
  - make
  - make -C zsdoc pdf
  - share/deploy_doc.sh
