# zinit.zsh

DKO_SOURCE="${DKO_SOURCE} -> zinit.zsh {"

zinit snippet --command 'https://github.com/davidosomething/git-ink/blob/master/git-ink'
zinit snippet --command 'https://github.com/davidosomething/git-my/blob/master/git-my'
zinit snippet --command 'https://github.com/davidosomething/git-take/blob/master/git-take'
zinit snippet --command 'https://github.com/davidosomething/vopen/blob/master/vopen-nofork'
zinit snippet --command 'https://github.com/davidosomething/vopen/blob/master/vopen'

# my fork of cdbk, ZSH hash based directory bookmarking
zinit light 'davidosomething/cdbk'

# ----------------------------------------------------------------------------
# Vendor: Commands
# ----------------------------------------------------------------------------

zinit snippet --command 'https://github.com/paulirish/git-open/blob/master/git-open'
zinit snippet --command 'https://github.com/paulirish/git-recent/blob/master/git-recent'
zinit snippet --command 'https://github.com/raylee/tldr/blob/master/tldr'

# replaces up() in shell/functions.sh
zinit light 'shannonmoeller/up'

# ----------------------------------------------------------------------------
# Vendor: ZSH extension
# ----------------------------------------------------------------------------

zinit snippet 'https://github.com/robbyrussell/oh-my-zsh/raw/master/plugins/colored-man-pages/colored-man-pages.plugin.zsh'

# In-line best history match suggestion
zinit light 'zsh-users/zsh-autosuggestions'
# zsh-autosuggestions -- clear the suggestion when entering completion select
# menu
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=("expand-or-complete")

zinit light 'zdharma/fast-syntax-highlighting'

# ----------------------------------------------------------------------------
# Vendor: Completion
# ----------------------------------------------------------------------------

zinit light 'zsh-users/zsh-completions'

zinit light 'gradle/gradle-completion'

zinit light 'lukechilds/zsh-better-npm-completion'

zinit light 'vasyharan/zsh-brew-services'

zinit light 'voronkovich/phpcs.plugin.zsh'

export DKO_SOURCE="${DKO_SOURCE} }"
