#!/usr/bin/env zsh

# .zshrc
# author: Seong Yong-ju ( @sei40kr )

export TERM='xterm-256color-italic'

if [[ "${+commands[tmux]}" == 1 ]] && [[ -z "$TMUX" ]]
then
  env \
      FZF_TMUX=1 \
      FZF_TMUX_HEIGHT='25%' \
      tmux new-session
  exit
fi

# zmodload zsh/zprof
zmodload zsh/zpty

export EDITOR="$(which nvim)"
export HISTFILE="${HOME}/.histfile"
export HISTSIZE=1000
export KEYTIMEOUT=1
export SAVEHIST=1000

export XDG_CONFIG_HOME="${HOME}/.config"

if [[ -d "${HOME}/.linuxbrew" ]]
then
  export XDG_DATA_DIRS="${HOME}/.linuxbrew/share:$XDG_DATA_DIRS";
fi

if [[ -e "${HOME}/.zsh_secret" ]]
then
  . "${HOME}/.zsh_secret"
fi

autoload -Uz add-zsh-hook
autoload -Uz cdr
autoload -Uz chpwd_recent_dirs
autoload -Uz zmv

setopt append_history
setopt auto_cd
setopt auto_list
setopt auto_menu
setopt auto_pushd
setopt extended_history
setopt glob_dots
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt interactive_comments
setopt no_beep
setopt print_eight_bit
setopt prompt_subst
setopt pushd_ignore_dups
setopt share_history
unsetopt list_beep

export GOPATH="${HOME}/.go"
PYENV_ROOT="${HOME}/.pyenv"
RBENV_ROOT="${HOME}/.rbenv"
ZPLUG_HOME="${HOME}/.zplug"

path=(
  '/usr/local/opt/coreutils/libexec/gnubin'
  '/usr/local/share/git-core/contrib'
  "${HOME}/.cabal/bin"
  "${HOME}/.cargo/bin"
  "${GOPATH}/bin"
  "${PYENV_ROOT}/bin"
  "${RBENV_ROOT}/bin"
  "${path[@]}"
)

source /dev/stdin <<EOM
$(pyenv init - zsh --no-rehash)
$(rbenv init - zsh --no-rehash)
EOM

. "${HOME}/.zinit/bin/zinit.zsh"

autoload -Uz _zinit

if [[ "${+_comps}" == 1 ]]
then
  _comps[zinit]=_zinit
fi

# zinit: Commands {{{
zinit ice from'gh-r' as'command' mv'gotcha_* -> gotcha'; zinit light 'b4b4r07/gotcha'
zinit ice as'command' cp'httpstat.sh -> httpstat' pick'httpstat'; zinit light 'b4b4r07/httpstat'
# }}}

# zinit: Libraries {{{
zinit snippet 'OMZ::lib/completion.zsh'
zinit snippet 'OMZ::lib/compfix.zsh'
zinit snippet 'OMZ::lib/git.zsh'
zinit snippet 'OMZ::lib/clipboard.zsh'
zinit snippet 'OMZ::lib/key-bindings.zsh'
# }}}

# zinit: Plugins {{{
zinit light 'b4b4r07/emoji-cli'
zinit light 'b4b4r07/enhancd'
zinit light 'djui/alias-tips'
zinit light 'mollifier/anyframe'
zinit light 'mollifier/cd-gitroot'
zinit light 'zdharma/fast-syntax-highlighting'
zinit light 'zsh-users/zsh-autosuggestions'
zinit ice pick'k.sh'; zinit light 'supercrabtree/k'
zinit snippet 'OMZ::plugins/colored-man-pages/colored-man-pages.plugin.zsh'
zinit snippet 'OMZ::plugins/dotenv/dotenv.plugin.zsh'
zinit snippet 'OMZ::plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh'
zinit snippet 'OMZ::plugins/gem/gem.plugin.zsh'
zinit snippet 'OMZ::plugins/git/git.plugin.zsh'
zinit snippet 'OMZ::plugins/gitignore/gitignore.plugin.zsh'
zinit snippet 'OMZ::plugins/jsontools/jsontools.plugin.zsh'
zinit snippet 'OMZ::plugins/pip/pip.plugin.zsh'
zinit snippet 'OMZ::plugins/rake/rake.plugin.zsh'
zinit snippet 'OMZ::plugins/react-native/react-native.plugin.zsh'
zinit ice if'[[ "${+commands[apt-get]}" ]]'; zinit snippet 'OMZ::plugins/ubuntu/ubuntu.plugin.zsh'
zinit snippet 'OMZ::plugins/zsh_reload/zsh_reload.plugin.zsh'
zinit snippet 'https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh'
zinit snippet 'https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh'
# }}}

# zinit: Completions {{{
zinit ice blockf; zinit light 'zsh-users/zsh-completions'
# }}}

autoload -Uz compinit; compinit

# zinit: Theme {{{
zinit ice pick'spaceship.zsh'; zinit light 'denysdovhan/spaceship-zsh-theme'
# }}}
